name: QWaypoints
version: ${project.version}
main: xyz.yarinlevi.waypoints.Waypoints
api-version: 1.16
author: Quapi

commands:
  waypoint:
    description: Main command.
    aliases: [wp, qwaypoints, qwp]
  wpadmin:
    aliases: [wpa, waypointadmin, qwaypointadmin, wpadmin]
    permission: waypoints.admin
  wpdebug:
    aliases: [wpd, waypointdebug]
    permission: waypoints.debug