name: QWaypoints
version: 2.0-PRE.RELEASE.1
main: me.yarinlevi.waypoints.Waypoints
api-version: 1.16
author: Quapi

commands:
  waypoint:
    description: Main command.
    aliases: [wp, qwaypoints]
  wpadmin:
    aliases: [wpa, waypointadmin, qwaypointadmin]
    permission: waypoints.admin