name: Waypoints
main: com.yarinlevi.Waypoints.Waypoints
version: 2.0 ALPHA
api-version: 1.15
commands:
  waypoint:
    description: Main command
    aliases: [wp, waypoints]
  wpadmin:
    description: Admin-level commands
    aliases: [wpa]
    permission: waypoints.admin
permissions:
  waypoints.admin:
    default: op
    description: Access to administration-level commands.